/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the the request body for editing customer.
 */
export interface CustomerEditFormBody {
  /**
   * client_id for this client. May be omitted for edits and must not change from the original
   */
  customerId?: string;
  /**
   * The name of the customer
   */
  name?: string;
  /**
   * The surname of the customer
   */
  surname?: string;
  /**
   * The birthdate of the customer DD/MM/YYYY
   */
  birthdate?: string;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the the request body for creating new customer.
 */
export interface CustomerNewFormBody {
  /**
   * The name of the customer
   */
  name: string;
  /**
   * The surname of the customer
   */
  surname: string;
  /**
   * The birthdate of the customer DD/MM/YYYY
   */
  birthdate: string;
}
