name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies with npm
        run: npm install

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm install
      - run: npm test

  release:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies with npm
        run: npm install

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build packages
        run: npm run build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
